apiVersion: composition.krateo.io/v1-1-5
kind: FireworksApp
metadata:
  name: fireworksapp-composition-2
  namespace: fireworksapp-system
spec:
  app:
    service:
      port: 31180
      type: NodePort
  argocd:
    application:
      destination:
        namespace: fireworks-app
        server: https://kubernetes.default.svc
      project: default
      source:
        path: chart/
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    namespace: krateo-system
  git:
    fromRepo:
      branch: main
      credentials:
        authMethod: basic
        secretRef:
          key: token
          name: github-repo-creds
          namespace: krateo-system
      name: krateo-v2-template-fireworksapp
      org: krateoplatformops
      path: skeleton/
      scmUrl: https://github.com
    insecure: true
    toRepo:
      apiUrl: https://api.github.com
      branch: main
      credentials:
        authMethod: basic
        secretRef:
          key: token
          name: github-repo-creds
          namespace: krateo-system
      initialize: true
      name: fireworksapp-test-v2
      org: krateoplatformops-archive
      path: /
      private: false
      scmUrl: https://github.com
    unsupportedCapabilities: true