apiVersion: composition.krateo.io/v1-1-13
kind: FireworksApp
metadata:
  name: fireworksapp-composition-copy
  namespace: fireworksapp-system
spec:
  app:
    service:
      port: 31180
      type: NodePort
  argocd:
    application:
      destination:
        namespace: fireworks-app
        server: https://kubernetes.default.svc
      project: default
      source:
        path: chart/
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    namespace: krateo-system
  git:
    fromRepo:
      branch: main
      credentials:
        authMethod: generic
        secretRef:
          key: token
          name: github-repo-creds
          namespace: krateo-system
      name: krateo-v2-template-fireworksapp
      org: krateoplatformops
      path: skeleton/
      scmUrl: https://github.com
    insecure: true
    toRepo:
      apiUrl: https://api.github.com
      branch: main
      credentials:
        authMethod: generic
        secretRef:
          key: token
          name: github-repo-creds
          namespace: krateo-system
      initialize: true
      org: your-organization # change here
      name: fireworksapp-test-v2-copy # you could also change here, but it is not necessary. This will be the name of the created repository
      path: /
      private: false
      scmUrl: https://github.com
    unsupportedCapabilities: true