---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: httpbin-endpoint
  namespace: dev-system
stringData:
  server: http://httpbin.org
  username: tik
  password: tok
---
apiVersion: widgets.ui.krateo.io/v1alpha1
kind: CardTemplate
metadata:
  name: card-dev-1
  namespace: dev-system
spec:
  app:
    icon: fa-solid fa-meteor
    color: GREEN
    title: ${ (.httpbin.json.firstName  + " " + .httpbin.json.lastName) }
    content: ${ .httpbin.json.location.city }
    tags: ${ .httpbin.json.hobbies | join(",") }
    actions:
    - name: crd
      enabled: true
      path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/postgresqls.composition.krateo.io"
      endpointRef:
        name: krateogateway-endpoint
        namespace: dev-system
      verb: DELETE
  api:
  - name: httpbin
    path: "/anything"
    endpointRef:
      name: httpbin-endpoint
      namespace: dev-system
    verb: GET
    headers:
    - 'Accept: application/json'
    payload: |
      {
        "firstName": "Charles",
        "lastName": "Doe",
        "age": 41,
        "location": {
          "city": "San Fracisco",
          "postalCode": "94103"
        },
        "hobbies": [
          "chess",
          "netflix"
        ]
      }
